config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get     'help'    => 'static_pages#help'
  get     'about'   => 'static_pages#about'
  get     'contact' => 'static_pages#contact'
  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  put     'checkin'  => 'checkins#create'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
        get :polling
    end
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :checkins,            only: [:new, :create, :edit, :update, :set_location]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_gmaps.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&sensor=false&client=&key=&libraries=geometry&language=&hl=®ion="></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div style='width: 750px;'>
  <div id="map" style='width: 750px; height: 250px;'></div>
</div>

<button id="checkinbtn" style="display:none;" onclick="setLocation()">Check in!</button>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
    if (<%= @user_lat.nil? || @user_lat.nil? %> ){
      handler.map.centerOn([42.697578, 23.32252])
    }
    else{
    handler.map.centerOn( <%= [@user_lat.to_f, @user_lng.to_f] %>);
    }
  });
  
  var setLat;
  var setLng;

  
  function setLocation() {
    $.ajax({
      url: "/checkin",
      type: "PUT",
      data: {  lat: setLat, 
               lng: setLng},
        success: function(data){
          window.location.reload();
        }
    });
    
  }
  
  var markerOnMap;
  
  function placeMarker(location) {    // simply method for put new marker on map
    document.getElementById("checkinbtn").style.display = 'block';
    if (markerOnMap) {
      markerOnMap.setPosition(location);
    }
    else {
      markerOnMap = new google.maps.Marker({
        position: location,
        map: handler.getMap()
      });
    }
  }

  google.maps.event.addListener(handler.getMap(), 'click', function(event) {    // event for click-put marker on map and pass coordinates to hidden fields in form
    placeMarker(event.latLng);
    setLat = event.latLng.lat();
    setLng = event.latLng.lng();
  });

</script>

app/views/shared/_home_logged_in.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section class="micropost_form">
      <span class="ajaxreloadpostform">
        <%= render 'shared/micropost_form' %>
        </span>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Where are your buddies right now?</h3>
    <%= render 'shared/gmaps' %>
    <h3>See some recent pix from ya friends, buddy.</h3>
    <%= render 'shared/pix' %>
    <h3>Micropost Feed</h3>
      <span class="ajaxreloadposts">
        <%= render 'shared/feed' %>
      </span>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
      setInterval(function () {
              $.ajax('microposts/<%= current_user.id %>/polling');
      } , 15000);
  }); 
</script>

app/views/shared/_home_not_logged_in.html.erb
<div class="center jumbotron">
  <h1>Welcome to ISN</h1>

  <h2>
    Don't forget about the towel and have fun.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, remote: true, :html => { :id => 'post_form' }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please chose a smaller file.')
    }
  })
</script>

app/views/shared/_pix.html.erb
<div class="owl-carousel">
  <% @feed_items.each do |micropost| %>
    <% if micropost.picture? %>
      <div class="item"><%= image_tag micropost.picture.url if micropost.picture? %></div>
    <% end %>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".owl-carousel").owlCarousel({
   
        autoPlay: 3000, //Set AutoPlay to 3 seconds
   
        items : 2,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,3]
   
    });
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>